export const laborSkills = [
   {name: 'Masonry'} ,
   {name: 'Carpentry'} ,
   {name: 'Painting'} ,
   {name: 'Drywall'} ,
   {name: 'Electrical'} ,
   {name: 'Plumbing'} ,
   {name: 'Telecom'} ,
   {name: 'Concrete'} ,
   {name: 'Roofing'} ,
   {name: 'IronWork'} ,
   {name: 'HVACWork'} ,
   {name: 'Tiles'} ,
   {name: 'Terrazo'} ,
   {name: 'Surveying'} ,
   {name: 'Operator'} ,
   {name: 'Demolition'} ,
]